blog/urls.py
from django.conf.urls import include, url
from . import views
app_name = 'blog'
urlpatterns = [
	url(r'^$',views.post_list),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
	url(r'^post/nuevo/$',views.post_nuevo,name='post_nuevo'),
	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_editar, name='post_editar'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
	autor = models.ForeignKey('auth.User')
	titulo = models.CharField(max_length=200)
	texto = models.TextField()
	fecha_creacion = models.DateTimeField(default=timezone.now)
	fecha_publicacion = models.DateTimeField(blank=True,null=True)

	def publicar(self):
		self.fecha_publicacion = timezone.now()
		self.save()

	def __str__(self):
		return self.titulo

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model= Post
		fields = ('titulo','texto',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.utils import timezone
from .forms import PostForm
# Create your views here.
def post_list(request):
	posts = Post.objects.filter(fecha_publicacion__lte=timezone.now()).order_by('fecha_publicacion')
	return render(request, 'blog/post_list.html', {'posts':posts})

def post_detail(request, pk):
        post = get_object_or_404(Post, pk=pk)
        return render(request, 'blog/post_detail.html', {'post': post})

def post_nuevo(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.autor = request.user
			post.fecha_publicacion = timezone.now()
			post.save()
			return redirect('blog:post_detail',pk=post.pk)
	else:
		form = PostForm()
	return render(request,'blog/post_editar.html',{'form':form})

def post_editar(request,pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit = False)
			post.autor = request.user
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_editar.html',{'form':form})

blog/templates/blog/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Fernando's Blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'blog:post_nuevo' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="">Fernando's Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

    {% block content %}
        <div class="post">
            {% if post.fecha_publicacion %}
                <div class="date">
                    {{ post.fecha_publicacion }}
                </div>
            {% endif %}
            <a class="btn btn-default" href="{% url 'blog:post_editar' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            <h1>{{ post.titulo }}</h1>
            <p>{{ post.texto|linebreaksbr }}</p>
        </div>
    {% endblock %}

blog/templates/blog/post_editar.html
{% extends 'blog/base.html' %}

    {% block content %}
        <h1>Nuevo Post</h1>
        <form method="POST" class="post-form">
        	{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Guardar</button>
        </form>
    {% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% for post in posts %}
            <div class="post">
                <div class="date">
                    {{ post.fecha_publicacion}}
                </div>
                <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.titulo }}</a></h1>
                <p>{{ post.texto|linebreaksbr }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}